### ISSUE TITLE
remove unused code

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/ReversingAStringExercise#1]
https://github.com/andulica/ReversingAStringExercise/blob/3dcedce4eb54a212b7ce889ba94263732e503c1f/ReversingAStringExercise/Program.cs#L9-L40

To keep your code clean you should remove old, unused code blocks.
If you want to "store" it for later references remember that you are on git and can look back at all the previous versions you have commited 😏 

But don't get me wrong, comments are not a bad thing per se 👆 
If you want to explain code for later reads, of course you can put a comment, but do that in a way that a human can read and understand it and not just outcomment old code

**Comment by andulica** [comment]
Seems that I have forgot to push my code on github repo ... this comments are deleted on my local machine
