### ISSUE TITLE
Start loop at 0

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/ReversingAStringExercise#5]
https://github.com/andulica/ReversingAStringExercise/blob/3dcedce4eb54a212b7ce889ba94263732e503c1f/ReversingAStringExercise/Program.cs#L47

See this as a bonus exercise, because it does not really change the result or flow of your program:
Can you think of a way to make your loop goes "forward" instead of starting from the last letter going to the first?

**Comment by andulica** [comment]
To make sure that I understood correctly . This loop instead iterating backwards you want it to iterate forward without changing the outcome of this solution? Example: banana to start iterating from b forward and save the character in a reverse variable of type String

**Comment by incredibleLeitman** [comment]
yes, exactly 👍 :D
