### ISSUE TITLE
refactor loop to be straight forward

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/ReversingAStringExercise#7]
https://github.com/andulica/ReversingAStringExercise/blob/54441de74707454262090a2d91d2a8e3d92faeef/ReversingAStringExercise/Program.cs#L13-L19
We already talked about this in the whatsapp group, in this loop you kinda use two separate variables to keep track of the current position, while instead you could just use the length and the current index only.

This was already discussed in issue #5

**Comment by andulica** [comment]
Hi! Looking backwards in our discussion I couldn't see that this solution was tagged as wrong... Just that I "Cheat" to mention you :)) . I thought that my solution was still correct and I left it as it is

**Comment by incredibleLeitman** [comment]
Haha yeah, your solution basically was indeed correct and worked fine 👍 
But I wanted to point out that your version was more complex and harder to follow than it could be ^^

I see you already have changed that and now it looks cleaner, don't you think?
So you can close this issue :D

**Comment by andulica** [comment]
Ofc I can see why your option is better, I saw that from the first time, just haven't saw that my solution was marked as an "issue" . Nevertheless I really appreciate your input and advices , just so that you don't wrongly understand me. I will close the topic here
